### ISSUE TITLE
Break out of template temporarily?

### ISSUE THREAD

**Issue by mrchris2000** [marcobiraghi/AdvancedTemplatesWP#1]
Hi,
I love this template, but have an issue trying to use it with the Microsoft Band SDK.
The SDK provides a 'built in' authentication page that displays when you call:
await bandClient.TileManager.AddTileAsync(myTile);
However when this is called in this template the authorization page is not displayed and the call times out (I've copy/pasted the sample code for now, the only thing different is the container template).
So, is there a means of temporarily breaking out of this template to enable the authorization page to render, then drop back into the template once the user has allow/denied?
Cheers,
Chris

**Comment by marcobiraghi** [comment]
Hi mrchriss2000!
I never used the MS Band SDK so I do not know exactly what's the authentication page you mention, Is it a page or a webview?
In theory my template is not going to touch the default behavior of navigation, and the pages are completely unaware of the existence of the container. My "container" is only an other ContentControl outside the application frame (a ContentControl too). It should not affect the behavior of the application and it it can't be disabled, because it's not a component but some layout. You can find more details about template basic idea here: http://developingwindows.com/universal-app-share-elements-between-pages/

If you use the default template, is everything works normally?

One possibility could be that the page is designed in the wrong place, because the SDK could add it into Appilcation.Current.Window instead into Frame. This is a guess, but it could be a test you can do. Call bandClient.TileManager.AddTileAsync(myTile); and breakpoint to see Application.Current.Frame content.

Thanks!
Marco

**Comment by mrchris2000** [comment]
So I've tried this with two projects now; one based on your template, the other just a default pivot template.
Pivot works fine.
This template fails.

I have tried breakpointing the call as your suggested, but it didn't yield much information.
I'm not so great at the Windowing stuff, is there a way to capture the initial rootFrame/Window before the template gets to it and switch to it when displaying a particular page?

**Comment by mrchris2000** [comment]
Same principal applies with Media elements actually; if I set the element to full screen the TopBarContent element stays on top.

I think there's a good case here for having a means of switching to a 'Raw' page in certain scenarios and a template page in others.

**Comment by marcobiraghi** [comment]
My template is a container for the normal root Frame, so... yes, you can restore original behavior simply setting Window.Current.Content to root frame (as default initialization), actually Window.Current.Content contains FrameContainer that contains root frame as Content. It's only an additional layer that can be skipped. But doing this layout probably need to rebuild (I think, if this it's not automatic. If no, try Window.Current.Activate(); and rootFrame.UpdateLayout()), and topbar and slide menu will disappear. To restore tempalate you need to recreate FrameContainer and set it as Window.Current.Content and set root frame as FrameContainer.Content (as initialization in App.cs > OnLaunched()). I've never tried this but it should work. I think that MS Band SDK put itself a page in Window.Current.Content like my template do, and this cause the problem. Sketchily, this is the solution... I'll do some trial and if I find a good solution I'll update the code 

Regarding MediaElement I'm shure that there aren't incompatibility, "Teach Me Sushi" app on the store use this template and media element and everything works like a sharm :) 
If you want to hide top bar, you can simply collapse it setting topBarGrid.Visibility = Visibility.Collapsed in FrameContainer.
